Support more outputs (#2)
* Support 100 outputs

* Add notice about max splits

* Fix orders

* Add test

* Limit maxsplit

* Quote

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: ci
 on:
   - push
 jobs:
-  action-test:
+  test:
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout
@@ -14,7 +14,24 @@ jobs:
           msg: '/release split v1'
       - name: Test results
         run: |
-          [[ ${{ steps.split.outputs._0 }} == "/release" ]] || (echo "test fail"; exit 1)
-          [[ ${{ steps.split.outputs._1 }} == "split" ]] || (echo "test fail"; exit 1)
-          [[ ${{ steps.split.outputs._2 }} == "v1" ]] || (echo "test fail"; exit 1)
-          [[ ${{ steps.split.outputs.length }} == "3" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._0 }}" == "/release" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._1 }}" == "split" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._2 }}" == "v1" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs.length }}" == "3" ]] || (echo "test fail"; exit 1)
+  test-100:
+    runs-on: ubuntu-18.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Run split action
+        id: split
+        uses: ./
+        with:
+          msg: '0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100'
+      - name: Test results
+        run: |
+          [[ "${{ steps.split.outputs._0 }}" == "0" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._50 }}" == "50" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._98 }}" == "98" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs._99 }}" == "99 100" ]] || (echo "test fail"; exit 1)
+          [[ "${{ steps.split.outputs.length }}" == "100" ]] || (echo "test fail"; exit 1)
